pod 'ECSlidingViewController', '~> 2.0'
pod 'AFNetworking', '~> 2.2.4'
pod 'Facebook-iOS-SDK', '~> 3.16'
pod 'SDWebImage', '~> 3.7'
pod 'YIPopupTextView', '~> 1.1.0'
pod 'CZPhotoPickerController'
pod 'EAIntroView', '~> 2.5.0'